language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: coverage run -m unittest discover -v
services:
  - redis-server
